# Generated by Django 2.0.2 on 2018-04-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doid', models.CharField(max_length=20)),
                ('match_status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-doid'],
            },
        ),
    ]
